In [1]:
import numpy as np

In [2]:
arr1D = np.array([1,2,3,4,5,6,7,8])
print(arr1D)

[1 2 3 4 5 6 7 8]


In [3]:
arr2D = np.array([[1,2,3,4,5,6],[8,9,10,11,12,13]])
print(arr2D)

[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]]


## Sorting

In [ ]:
np.sort(arr)

## Concatenate

In [ ]:
np.concatenate((a, b))

# Zeros Matrix

In [4]:
zeros = np.zeros((3, 4))  # 3x4 matrix of zeros
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones Matrix 

In [5]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


# Empty (uninitialized - faster but random values)

In [6]:
empty = np.empty((2, 2))
print(empty)

[[0. 0.]
 [0. 0.]]


# Identity matrix

In [7]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Arange

In [8]:
arrArrange = np.arange(0, 10, 2)
print(arrArrange)

[0 2 4 6 8]


# Linspace (evenly spaced numbers)

In [9]:
arrLinespace = np.linspace(0, 1, 5)
print(arrLinespace)

[0.   0.25 0.5  0.75 1.  ]


# Random arrays (VERY important for ML)

In [10]:
random_arr = np.random.random((3, 3))
random_int = np.random.randint(0, 10, (3, 3))
normal = np.random.randn(3, 3)

In [11]:
print(random_arr)
print("__________________________________")

print(random_int)
print("__________________________________")

print(normal)
print("__________________________________")

[[0.49855506 0.41938113 0.77855582]
 [0.41850723 0.79584114 0.16205667]
 [0.82497711 0.40675264 0.53651174]]
__________________________________
[[6 1 4]
 [3 3 9]
 [8 3 7]]
__________________________________
[[ 1.12708026  1.23678379  0.52658929]
 [ 0.61628888 -0.66802103  0.05305558]
 [ 0.67974429  0.48465752  2.51812822]]
__________________________________


# Array Function

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)    # (2, 4) - dimensions
print("__________________________________")
print(arr.ndim)     # 2 - number of dimensions
print("__________________________________")
print(arr.size)     # 8 - total number of elements
print("__________________________________")
print(arr.dtype)    # dtype('int64') - data type
print("__________________________________")
print(arr.itemsize) # 8 - size of each element in bytes

(2, 4)
__________________________________
2
__________________________________
8
__________________________________
int64
__________________________________
8


# Array Slicing

In [13]:
arr = np.array([10, 20, 30, 40, 50])


print(arr[0])      # 10
print("-----------------------------")
print(arr[-1])     # 50 (last element)
print("-----------------------------")

# Slicing
print(arr[1:4])    # [20 30 40]
print("-----------------------------")
print(arr[:3])     # [10 20 30]
print("-----------------------------")
print(arr[::2])    # [10 30 50] (every 2nd element)
print("-----------------------------")


print("2D")
print("***********")
# 2D arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0, 1])      # 2 (row 0, col 1)
print("-----------------------------")
print(arr2d[1])         # [4 5 6] (entire row)
print("-----------------------------")
print(arr2d[:, 1])      # [2 5 8] (entire column)
print("-----------------------------")
print(arr2d[0:2, 1:3])  # [[2 3] [5 6]] (submatrix)
print("-----------------------------")

10
-----------------------------
50
-----------------------------
[20 30 40]
-----------------------------
[10 20 30]
-----------------------------
[10 30 50]
-----------------------------
2D
***********
2
-----------------------------
[4 5 6]
-----------------------------
[2 5 8]
-----------------------------
[[2 3]
 [5 6]]
-----------------------------


# Boolean Indexing (Critical for ML)

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean mask
mask = arr > 3
print(mask)         # [False False False True True True]
print("-----------------------------")
print(arr[mask])    # [4 5 6]
print("-----------------------------")

# Direct filtering
print(arr[arr > 3]) # [4 5 6]
print("-----------------------------")

# Multiple conditions
print(arr[(arr > 2) & (arr < 5)])  # [3 4]
print("-----------------------------")


[False False False  True  True  True]
-----------------------------
[4 5 6]
-----------------------------
[4 5 6]
-----------------------------
[3 4]
-----------------------------


# Reshaping Arrays

In [15]:
arr = np.arange(12)  # [0 1 2 3 4 5 6 7 8 9 10 11]

# Reshape
reshaped = arr.reshape(3, 4)  # 3x4 matrix
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Flatten back
flattened = reshaped.flatten()  # or .ravel()


# Transpose
transposed = reshaped.T  # 4x3 matrix

# Add new axis (important for ML)
arr = np.array([1, 2, 3])
arr_col = arr[:, np.newaxis]  # Column vector (3, 1)
arr_row = arr[np.newaxis, :]  # Row vector (1, 3)

## flatten() vs ravel()
1 - Flatten()

-> Any changes to the flattened result won’t affect the original array.
-> mostly use to flattern dimensional Array into flatten arrayt in a diffrent variable.

2 - ravel()

-> it changes the original Array.

# Increasing Dimensions

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

# Maths Function

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# A 2D array for axis examples
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

In [17]:
# Element-wise operations are simple
print("Addition:", np.add(arr1, arr2))
print("Multiplication:", np.multiply(arr1, 10))
print("Square Root:", np.sqrt(arr1))
print("Power:", np.power(arr1, 2))

Addition: [11 22 33 44 55]
Multiplication: [10 20 30 40 50]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Power: [ 1  4  9 16 25]


### Aggregation Functions

### the function formulate/ works on all element in the array

In [18]:
print("Sum (all elements):", np.sum(matrix))
print("Mean (all elements):", np.mean(matrix))
print("Max value:", np.max(matrix))
print("Index of max value:", np.argmax(matrix))

Sum (all elements): 21
Mean (all elements): 3.5
Max value: 6
Index of max value: 5


In [19]:
# Using the axis parameter

print("Sum of each column (axis=0):", np.sum(matrix, axis=0))
print("Mean of each row (axis=1):", np.mean(matrix, axis=1))

Sum of each column (axis=0): [5 7 9]
Mean of each row (axis=1): [2. 5.]


# Array Operations

In [ ]:
# Element-wise operations (NO LOOPS NEEDED!)
print(arr + 5)      # [6 7 8 9]
print(arr * 2)      # [2 4 6 8]
print(arr ** 2)     # [1 4 9 16]
print(1 / arr)      # [1.   0.5  0.33 0.25]

# Array with array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # [5 7 9]
print(arr1 * arr2)  # [4 10 18] - element-wise multiplication